### ISSUE TITLE
LUA version support

### ISSUE THREAD

**Issue by dlehammer** [queueit/KnownUser.V3.Lua#6]
Hi Queue-IT gurus,

This [README](https://github.com/queueit/KnownUser.V3.Lua/blob/master/README.md) states

> **Using it with Lua versions higher than this (ex. v.5.3) will not work.**

On the other hand the [Nginx README](https://github.com/queueit/KnownUser.V3.Lua/blob/master/Examples/Nginx/README.md) states

> The following implementation steps have been developed and tested using this [Docker image](https://github.com/fabiocicerchia/nginx-lua).

The referenced Docker image utilizes [LUA v5.4](https://github.com/fabiocicerchia/nginx-lua/blob/f1351f4d12975c471faf78ff49c87217dd126f2f/Dockerfile#L31).

Is the initial warning still valid, and if so how does the version mismatch symptom manifest itself **?** 

Thanks in advance :)

**Comment by frwiqueueit** [comment]
When our Lua SDK was initially developed we used Lua 5.1 and Apache as runtime environment. 
The Nginx was introduced later. As you state the docker image uses a newer version. 
In the end I guess it depends on your setup if it runs or not. What we experienced was runtime exceptions as far as I remember.

**Comment by frwiqueueit** [comment]
@dlehammer Can you verify it runs with Nginx on Lua 5.4? Then I will update the readme

**Comment by dlehammer** [comment]
Hi @frwiqueueit,

Good point, I've checked the vendor provided image in our customers setup - and it utilises LUA v5.1.

So v5.4 will need verification elsewhere

(Sounds puzzling a "minor" upgrade breaks backwards-compatibility)
